---
- name: Install LAMP stack packages
  apt:
    name:
      - apache2
      - mysql-server
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Ensure MySQL is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: ''
    state: present
    host_all: true
  ignore_errors: yes

- name: Create MySQL database
  mysql_db:
    name: "{{ mysql_db_name }}"
    state: present

- name: Create MySQL user with privileges
  mysql_user:
    name: "{{ mysql_db_user }}"
    password: "{{ mysql_db_password }}"
    priv: "{{ mysql_db_name }}.*:ALL"
    state: present

- name: Ensure Apache is started and enabled
  service:
    name: apache2
    state: started
    enabled: yes

- name: Deploy test PHP file
  template:
    src: test.php.j2
    dest: "{{ apache_test_file }}"
    mode: '0644'

- name: Restart Apache to apply changes
  service:
    name: apache2
    state: restarted
