---
- name: Ensure a specific line is present in /etc/hosts
  hosts: all
  become: yes  # Use become to escalate privileges
  tasks:
    - name: Add a line to /etc/hosts if it doesn't already exist
      lineinfile:
        path: /etc/hosts
        line: "127.0.0.1 example.com"
        state: present

