---
- name: Ensure nginx container is running
  hosts: localhost
  become: yes
  tasks:
    - name: Start nginx container
      docker_container:
        name: nginx_container
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "9080:80"  # Map port 80 on the host to port 80 on the container
